# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
inhibit_all_warnings!#忽略所有pods里面的警告
target 'KaiDemo' do

pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'FMDB'
pod 'MJExtension'
pod 'MBProgressHUD' #hud提示
pod 'JPush'
pod 'YYModel'

end


target 'KaiDemoTests' do

end

target 'KaiDemoUITests' do

end
